#!/bin/sh
cd /home/newsstream
git stash
git pull
git stash apply
./env/bin/pip install -r requirements.txt
./manager.py update
pkill -HUP uwsgi
service nginx stop
rm -fr /tmp/wellenmann.de-cache/*
service nginx start
./manager.py scrape
